- hosts: all                    # Admitimos cualquier host para la ejecución del archivo
  become: true                  # Permiso para ejecutar las órdenes como root
  remote_user: vagrant          # Será vagrant el que utilice este archivo
  
  tasks:
  
    - name: Update package list
      command: sudo apt-get update
      
    - name: Add Python3.6 repository
      apt: 
        repo: ppa:/deadsnakes/ppa
        state: present
        
    - name: Install Git
      apt:
        name: git
        state: present
      
    - name: Install Python3.6
      apt: 
        pkg: python3.6 
        state: present      
      
    - name: Install pip3
      apt:
        pkg: python3-pip
        state: present
      
    - name: Clone repository
      git:
        repo: https://github.com/aitorSDL/proyecto-iv-1819
        dest: proyecto-iv-1819/
      
    -name: Install requirements
      command: pip3 install -r requirements.txt
